#!/bin/bash

RRO_NAME='UpdaterOverlayEXTRA'
CURRENT_YEAR=$(date "+%Y")

[ -z $1 ] && echo 'cringe' && exit

for version in $@; do
    [ -d ${RRO_NAME}/${version} ] && rm -rf ${RRO_NAME}/${version}
    cp -r ${RRO_NAME}/base ${RRO_NAME}/${version}
    sed -i "s/lineage-base/lineage-${version}/g; s/{curr_year}/${CURRENT_YEAR}/g" ${RRO_NAME}/${version}/res/values/string.xml
done
