# Board specific SELinux policy variable definitions
VENDOR_EXTRA_SEPOLICY_PATH := $(VENDOR_EXTRA_PATH)/sepolicy

PRODUCT_PRIVATE_SEPOLICY_DIRS += \
    $(VENDOR_EXTRA_SEPOLICY_PATH)/private

PRODUCT_PUBLIC_SEPOLICY_DIRS += \
    $(VENDOR_EXTRA_SEPOLICY_PATH)/public

BOARD_VENDOR_SEPOLICY_DIRS += \
    $(VENDOR_EXTRA_SEPOLICY_PATH)/vendor
