# Board specific SELinux policy variable definitions
VENDOR_EXTRA_SEPOLICY_PATH := $(VENDOR_EXTRA_PATH)/sepolicy

SYSTEM_EXT_PRIVATE_SEPOLICY_DIRS += \
    $(VENDOR_EXTRA_SEPOLICY_PATH)/private

SYSTEM_EXT_PUBLIC_SEPOLICY_DIRS += \
    $(VENDOR_EXTRA_SEPOLICY_PATH)/public

BOARD_VENDOR_SEPOLICY_DIRS += \
    $(VENDOR_EXTRA_SEPOLICY_PATH)/vendor
