#!/bin/bash

CURRENT_YEAR=$(date "+%Y")

[ -z $1 ] && echo 'cringe' && exit

for version in $@; do
    [ -d ${version} ] && rm -rf ${version}
    cp -r base ${version}
    sed -i "s/lineage-base/lineage-${version}/g; s/{curr_year}/${CURRENT_YEAR}/g" ${version}/res/values/string.xml
done
